id: IEE3307B3
legacy_id: P010337
ocr_import_info:
  bdrc_scan_id: W3CN3328
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T19:43:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:30:29.824223+00:00'
last_modified: 2022-09-03 21:33:26.979080
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3328
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3328
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇིགས་མེད་རོལ་པའི་རྡོ་རྗེ།
  author: འཇིགས་མེད་རོལ་པའི་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9718798655823551
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I3CN3547:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3547
      total_pages: 610
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3CN3547.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9740455462958659
    legacy_id: v007
  I3CN3543:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3543
      total_pages: 584
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN3543.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9713860698024745
    legacy_id: v003
  I3CN3545:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3545
      total_pages: 786
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3CN3545.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9702831315146696
    legacy_id: v005
  I3CN3546:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3546
      total_pages: 432
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3CN3546.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9672862687452215
    legacy_id: v006
  I3CN3548:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3548
      total_pages: 501
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I3CN3548.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9695919609823985
    legacy_id: v008
  I3CN3542:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3542
      total_pages: 524
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN3542.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9746388297618699
    legacy_id: v002
  I3CN3541:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3541
      total_pages: 566
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN3541.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9745274593833332
    legacy_id: v001
  I3CN3544:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3544
      total_pages: 604
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3CN3544.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9727089186608603
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
